// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMEpYzlUw-9YG7VfCaMztzjMvSIODcvnw',
    appId: '1:753526643614:web:55da0c8f405f5cc482548f',
    messagingSenderId: '753526643614',
    projectId: 'fyp-tailorsapp',
    authDomain: 'fyp-tailorsapp.firebaseapp.com',
    storageBucket: 'fyp-tailorsapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDclAtw6WFncwSwFe5JUDvPIhD8rSb0n40',
    appId: '1:753526643614:android:1664f8c475703c9a82548f',
    messagingSenderId: '753526643614',
    projectId: 'fyp-tailorsapp',
    storageBucket: 'fyp-tailorsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl5CfGXO8idBq_DDBiUy9aDoTRgIZlTN8',
    appId: '1:753526643614:ios:2e8472e3171b44b682548f',
    messagingSenderId: '753526643614',
    projectId: 'fyp-tailorsapp',
    storageBucket: 'fyp-tailorsapp.firebasestorage.app',
    iosBundleId: 'com.example.tailorsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl5CfGXO8idBq_DDBiUy9aDoTRgIZlTN8',
    appId: '1:753526643614:ios:2e8472e3171b44b682548f',
    messagingSenderId: '753526643614',
    projectId: 'fyp-tailorsapp',
    storageBucket: 'fyp-tailorsapp.firebasestorage.app',
    iosBundleId: 'com.example.tailorsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMEpYzlUw-9YG7VfCaMztzjMvSIODcvnw',
    appId: '1:753526643614:web:8d9e4c36667dd7c782548f',
    messagingSenderId: '753526643614',
    projectId: 'fyp-tailorsapp',
    authDomain: 'fyp-tailorsapp.firebaseapp.com',
    storageBucket: 'fyp-tailorsapp.firebasestorage.app',
  );
}
